package mqtt

type MessageType int

const (
	MESSAGE_TYPE_RESERVED1   MessageType = 0
	MESSAGE_TYPE_CONNECT     MessageType = 1
	MESSAGE_TYPE_CONNACK     MessageType = 2
	MESSAGE_TYPE_PUBLISH     MessageType = 3
	MESSAGE_TYPE_PUBACK      MessageType = 4
	MESSAGE_TYPE_PUBREC      MessageType = 5
	MESSAGE_TYPE_PUBREL      MessageType = 6
	MESSAGE_TYPE_PUBCOMP     MessageType = 7
	MESSAGE_TYPE_SUBSCRIBE   MessageType = 8
	MESSAGE_TYPE_SUBACK      MessageType = 9
	MESSAGE_TYPE_UNSUBSCRIBE MessageType = 10
	MESSAGE_TYPE_UNSUBACK    MessageType = 11
	MESSAGE_TYPE_PINGREQ     MessageType = 12
	MESSAGE_TYPE_PINGRESP    MessageType = 13
	MESSAGE_TYPE_DISCONNECT  MessageType = 14
	MESSAGE_TYPE_RESERVED2   MessageType = 15
)

type ReturnCode int

const (
	CONNECTION_ACCEOTED ReturnCode = 1
	CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION ReturnCode = 2
	CONNECTION_REFUSED_IDENTIFIER_REJECTED ReturnCode = 3
	CONNECTION_REFUSED_SERVER_UNAVAILABLE ReturnCode = 4
	CONNECTION_REFUSED_BAD_USER_NAME_OR_PASSWORD ReturnCode = 5
	CONNECTION_REFUSED_NOT_AUTHORIZED ReturnCode = 6
)
